server {
    listen 8080;
    server_name yt-session-bridge;

    location = /get_pot {
        proxy_pass http://yt-session-generator:8080/token;
    }

    location = /update {
        proxy_pass http://yt-session-generator:8080/update;
    }
}
